### ISSUE TITLE
/change-access-code UI Refactoring

### ISSUE THREAD

**Issue by ronneylogs** [SFU-Blueprint/Pedals#46]
## Problem
The current page at `/change-access-code` differs from the layout in the Figma design and lacks the use of reusable components in its code.

### Expected Design
![{AE37BCDA-2042-4343-84C7-995898C0F8B0}](https://github.com/user-attachments/assets/bc189b34-ca78-4348-a8c7-795f00940180)

### Current design
![{B4C203B8-4514-4BFB-A7BF-D9D14458345A}](https://github.com/user-attachments/assets/c8846080-1cac-46cc-966a-403ab14512be)

## Instructions
1. Pull the latest changes from the `develop` branch.
2. Start the server by running `npm run dev` (navigate to the `src/` folder and run `npm ci` if needed). Then visit `localhost:3000/change-access-code`.
3. Edit the code in this file: [change-access-code/page.tsx](https://github.com/SFU-Blueprint/Pedals/blob/develop/src/app/(ui)/(manager)/change-access-code/page.tsx).
4. Ensure to use [reusable components](https://github.com/SFU-Blueprint/Pedals/tree/develop/src/app/components) wherever applicable.
5. Create a pull request and tag @dangminhduc1101 for review.

**Comment by ronneylogs** [comment]
<img width="500" alt="Screenshot 2024-09-05 at 4 51 00 PM" src="https://github.com/user-attachments/assets/07fee1dc-f96e-4691-8ef2-46b0f61c300e">

Change this such that it uses the global component instead

**Comment by dangminhduc1101** [comment]
Resolved with commit [fbff021](https://github.com/SFU-Blueprint/Pedals/commit/fbff021dad4b69b43d653dc5dc612059f2f40ecb)
