### ISSUE TITLE
/export Frontend Implementation

### ISSUE THREAD

**Issue by dangminhduc1101** [SFU-Blueprint/Pedals#73]
## Problem
The front end of the export page does not match the desired design.

### Expected design
See [Figma](https://www.figma.com/design/1hpRLtveOgIDcvLeFu2rMM/Logbook?node-id=805-11881&node-type=canvas&t=N8skzRTI6QoCCaYZ-0)

## Instructions
1. Pull the latest changes from the `develop` branch.
2. Start the server by running `npm run dev` (if necessary, navigate to the `src/` folder and run `npm ci` first). Navigate to localhost:3000/export
3. Modify the code to align with the design. Make sure to utilize global components located in `@/components/` and relevant utility functions and constants in `@/utils/` as needed.
4. Submit a pull request and tag @dangminhduc1101 for review.

**Comment by qvd808** [comment]
@dangminhduc1101 Updated the front end for export page. The design is based on Figma. Let's me know if there is any issue
