### ISSUE TITLE
/manage/people Radio button + Filtering Bugs

### ISSUE THREAD

**Issue by terry9041** [SFU-Blueprint/Pedals#78]
<h2>Problems</h2>

1. After clicking "UNDER 18" or "INACTIVE" radio button to filter results, when the result is empty, "SELECT ALL" radio button is still automatically checked. It should not be checked as it confuses the user.

![image](https://github.com/user-attachments/assets/a9312f42-7a96-448c-acab-92485c699564)

2. After checking "SELECT ALL" option, the option cannot be turned off by clicking the "SELECT ALL" text.

<h2>Instructions</h2>

1. Pull the latest changes from the `develop `branch.
2. Start the server by running `npm run dev` (if necessary, navigate to the `src/` folder and run `npm ci` first). Navigate to localhost:3000/manage/people
3. Modify the logic of the radio button to fix the above issues.
4. Submit a pull request and tag @dangminhduc1101  for review.

**Comment by dangminhduc1101** [comment]
Fixed with #[bcbaebf](https://github.com/SFU-Blueprint/Pedals/commit/bcbaebf75393fef325e18b77efec7aa0bed533c4)
